CREATE USER coordenador WITH PASSWORD '123456';
CREATE USER aluno WITH PASSWORD 'senhaaluno';

GRANT SELECT, INSERT, UPDATE ON ALUNO TO coordenador;
GRANT SELECT ON CURSO, DISCIPLINA, PROFESSOR, TURMA, MATRICULA TO coordenador;

GRANT SELECT ON ALUNO, MATRICULA TO aluno;

REVOKE UPDATE ON MATRICULA FROM aluno;
